In [3]:
import pandas as pd
url = "https://raw.githubusercontent.com/nkmwicz/data-for-students/refs/heads/main/soccer-players.csv"
df = pd.read_csv(url)
df.head()

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,right,184.0,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,left,190.0,NaN,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,NaN,NaN,NaN,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,NaN,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,right,194.0,NaN,IFM,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,FC Bayern München,100000.0,3000000.0

In [4]:
# df.to_csv("./data/soccer-players.csv", index=False)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32403 entries, 0 to 32402
Data columns (total 23 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   player_id                             32403 non-null  int64
 1   first_name                            30345 non-null  object
 2   last_name                             32403 non-null  object
 3   name                                  32403 non-null  object
 4   last_season                           32403 non-null  int64
 5   current_club_id                       32403 non-null  int64
 6   player_code                           32403 non-null  object
 7   country_of_birth                      29600 non-null  object
 8   city_of_birth                         29942 non-null  object
 9   country_of_citizenship                32023 non-null  object
 10  date_of_birth                         32356 non-null  object
 11  sub_position                          32218 non-null  object
 12  position                              32403 non-null  object
 13  foot                                  29810 non-null  object
 14  height_in_cm                          30059 non-null  float64
 15  contract_expiration_date              20272 non-null  object
 16  agent_name                            16388 non-null  object
 17  image_url                             32403 non-null  object
 18  url                                   32403 non-null  object
 19  current_club_domestic_competition_id  32403 non-null  object
 20  current_club_name                     32403 non-null  object
 21  market_value_in_eur                   30869 non-null  float64
 22  highest_market_value_in_eur           30869 non-null  float64
dtypes: float64(3), int64(3), object(17)
memory usage: 5.7+ MB

In [6]:
df.describe()

,player_id,last_season,current_club_id,height_in_cm,market_value_in_eur,highest_market_value_in_eur
count,3.240300e+04,32403.000000,32403.000000,30059.000000,3.086900e+04,3.086900e+04
mean,3.445789e+05,2019.337777,4809.252045,182.291161,1.611350e+06,3.675045e+06
std,2.806831e+05,3.965914,11601.982978,6.971224,6.362017e+06,9.653897e+06
min,1.000000e+01,2012.000000,3.000000,17.000000,1.000000e+04,1.000000e+04
25%,1.066980e+05,2016.000000,403.000000,178.000000,1.000000e+05,2.750000e+05
50%,2.824210e+05,2020.000000,1071.000000,183.000000,2.500000e+05,8.000000e+05
75%,5.242085e+05,2023.000000,3060.000000,187.000000,7.000000e+05,2.800000e+06
max,1.309800e+06,2024.000000,110302.000000,207.000000,2.000000e+08,2.000000e+08

In [7]:
df["height_in_cm"].mean()

np.float64(182.29116071725608)

In [8]:
df["height_in_cm"].median()

183.0

In [9]:
df["height_in_cm"].mode()[0]

np.float64(180.0)

In [10]:
df["height_in_cm"].var()

48.59796930610728

In [11]:
df["height_in_cm"].std()

6.971224376399549

In [12]:
min_ht = df["height_in_cm"].min()

In [13]:
max_ht = df["height_in_cm"].max()

In [14]:
range_ht = max_ht - min_ht

In [15]:
print(f"range = {range_ht}, min = {min_ht}, max = {max_ht}")

range = 190.0, min = 17.0, max = 207.0

In [16]:
# %conda install scipy

In [17]:
from scipy import stats

In [18]:
pd_skew = df["height_in_cm"].skew()
scipy_skew = stats.skew(df["height_in_cm"], nan_policy = "omit")
print(f"pd_skew = {pd_skew}, scipy_skew = {scipy_skew}")

pd_skew = -1.7751475048518246, scipy_skew = -1.7750589204621978

In [19]:
pd_kurt = df["height_in_cm"].kurt()
scipy_kirt = stats.kurtosis(df["height_in_cm"].dropna())
scipy_kirt_omit = stats.kurtosis(df["height_in_cm"], nan_policy = "omit")
print(f"pd_kurt = {pd_kurt}, scipy_kurt = {scipy_kirt}, scipy_kurt_omit = {scipy_kirt_omit}")

pd_kurt = 40.3723954752419, scipy_kurt = 40.36548066183285, scipy_kurt_omit = 40.36548066183285

In [25]:
import pandas as pd
from scipy import stats
import numpy as np

def eda(df: pd.DataFrame) -> pd.DataFrame:
    
    """
    Do stat eval on dataframe
    
    Args:
        df (pd.DataFrame): Dataframe to evaluate
    Returns:
        pd.DataFrame: New Dataframe with column evals
    """
    
    data = []
    index = df.columns
    new_columns = [
        "is_numeric",
        "min",
        "max",
        "range",
        "std",
        "num_na",
        "perc_na",
        "num_unique",
        "unique_vals"
        ]
    total_vals = len(df)
    for col in df.columns:
        num_na = df[col].isna().sum()
        perc_na = round(num_na / total_vals, 4)
        num_unique = df[col].nunique()
        if pd.api.types.is_numeric_dtype(df[col]):
            is_num = True
            min = df[col].min()
            max = df[col].max()
            rng = max - min
            std = round(df[col].std(), 4)
            unique_vals = np.nan
            row = [is_num, min, max, rng, std, num_na, perc_na, num_unique, unique_vals]
            data.append(row)
        else:
            is_num = False
            min = np.nan
            max = np.nan
            rng = np.nan
            std = np.nan
            unique_vals = df[col].unique() if num_unique < 8 else np.nan
            row = [is_num, min, max, rng, std, num_na, perc_na, num_unique, unique_vals]
            data.append(row)
    new_df = pd.DataFrame(data = data, columns = new_columns, index = index)
    return new_df

In [26]:
cats_df = eda(df)
cats_df

,is_numeric,min,max,range,std,num_na,perc_na,num_unique,unique_vals
player_id,True,10.0,1309800.0,1309790.0,2.806831e+05,0,0.0000,32403,NaN
first_name,False,NaN,NaN,NaN,NaN,2058,0.0635,6966,NaN
last_name,False,NaN,NaN,NaN,NaN,0,0.0000,23701,NaN
name,False,NaN,NaN,NaN,NaN,0,0.0000,31708,NaN
last_season,True,2012.0,2024.0,12.0,3.965900e+00,0,0.0000,13,NaN
current_club_id,True,3.0,110302.0,110299.0,1.160198e+04,0,0.0000,437,NaN
player_code,False,NaN,NaN,NaN,NaN,0,0.0000,31667,NaN
country_of_birth,False,NaN,NaN,NaN,NaN,2803,0.0865,185,NaN
city_of_birth,False,NaN,NaN,NaN,NaN,2461,0.0759,8537,NaN
country_of_citizenship,False,NaN,NaN,NaN,NaN,380,0.0117,183,NaN
date_of_birth,False,NaN,NaN,NaN,NaN,47,0.0015,9272,NaN
sub_position,False,NaN,NaN,NaN,NaN,185,0.0057,13,NaN
position,False,NaN,NaN,NaN,NaN,0,0.0000,5,"[Attack, Goalkeeper, Defender, Midfield, Missing]"
foot,False,NaN,NaN,NaN,NaN,2593,0.0800,3,"[right, left, nan, both]"
height_in_cm,True,17.0,207.0,190.0,6.971200e+00,2344,0.0723,52,NaN
contract_expiration_date,False,NaN,NaN,NaN,NaN,12131,0.3744,114,NaN
agent_name,False,NaN,NaN,NaN,NaN,16015,0.4942,2833,NaN
image_url,False,NaN,NaN,NaN,NaN,0,0.0000,26561,NaN
url,False,NaN,NaN,NaN,NaN,0,0.0000,32403,NaN
current_club_domestic_competition_id,False,NaN,NaN,NaN,NaN,0,0.0000,14,NaN
current_club_name,False,NaN,NaN,NaN,NaN,0,0.0000,437,NaN
market_value_in_eur,True,10000.0,200000000.0,199990000.0,6.362017e+06,1534,0.0473,129,NaN
highest_market_value_in_eur,True,10000.0,200000000.0,199990000.0,9.653897e+06,1534,0.0473,206,NaN

In [29]:
cats_df.loc[cats_df["is_numeric"] == True]

,is_numeric,min,max,range,std,num_na,perc_na,num_unique,unique_vals
player_id,True,10.0,1309800.0,1309790.0,2.806831e+05,0,0.0000,32403,NaN
last_season,True,2012.0,2024.0,12.0,3.965900e+00,0,0.0000,13,NaN
current_club_id,True,3.0,110302.0,110299.0,1.160198e+04,0,0.0000,437,NaN
height_in_cm,True,17.0,207.0,190.0,6.971200e+00,2344,0.0723,52,NaN
market_value_in_eur,True,10000.0,200000000.0,199990000.0,6.362017e+06,1534,0.0473,129,NaN
highest_market_value_in_eur,True,10000.0,200000000.0,199990000.0,9.653897e+06,1534,0.0473,206,NaN